version: '3.8'

services:

  odoo:
    image: odoo:17
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_custom_addons:/mnt/extra-addons
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo_db  # Set a custom database name
      - PGHOST=db
      - MASTER_PASSWORD=ordior2424$

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo_db  # Make sure the PostgreSQL container uses this name
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

volumes:
  odoo_data:
  odoo_custom_addons:
  odoo_db_data:
